### ISSUE TITLE
Missing note in Order notes

### ISSUE THREAD

**Issue by alexanderjuulj** [onpayio/woocommerce#18]
Hi!

I'm experiencing some issues with orders. The transactions go through, the amount is created, authorized and auto-captured in OnPay, but with every once-in-a-while the **Order Notes** in WooCommerce doesn't add the OnPay message of it being authorized. The orders where this happens doesn't automically create and send the product (digital gift cards). 

The transaction history look the same in all the orders. The only difference seems to be the **Order Notes**.

**Succesful order**

![Transaktion-onpay](https://user-images.githubusercontent.com/37003848/105057912-5dbd5380-5a7e-11eb-9294-6f0f88b9fedb.png)

**Failed order**:

![Transaktion-fejl-onpay](https://user-images.githubusercontent.com/37003848/105057914-5e55ea00-5a7e-11eb-81b3-aa1482786f34.png)

**Comment by ebbesmoeller** [comment]
The order note for the authorized state is added, when the plugin receives the callback from OnPay. This happens in the callback method: https://github.com/onpayio/woocommerce/blob/master/woocommerce-onpay.php#L143

Please make sure that these callbacks are received by your Wordpress/WooCommerce installation. :-)

**Comment by ebbesmoeller** [comment]
Closing, since no response
